### ISSUE TITLE
ValueError:Filter must not be larger than  the  input :Filter:(5,5)  Input :(4,4)

### ISSUE THREAD

**Issue by YuanEZhou** [yenchenlin/pix2pix-tensorflow#2]
When i run the code ,I got  the error.  Can you tell me how to fix it .    Thanks.

**Comment by yenchenlin** [comment]
Can you provide which version of tensorflow are you using?

**Comment by YuanEZhou** [comment]
0.10

**Comment by yenchenlin** [comment]
Please review README again 😄 

### Prerequisites
- Linux
- Python with numpy
- NVIDIA GPU + CUDA 8.0 + CuDNNv5.1
- TensorFlow 0.11

**Comment by YuanEZhou** [comment]
e5 = self.g_bn_e5(conv2d(lrelu(e4), self.gf_dim*8, name='g_e5_conv'))
        # e5 is (8 x 8 x self.gf_dim*8)
 e6 = self.g_bn_e6(conv2d(lrelu(e5), self.gf_dim*8, name='g_e6_conv'))
        **# e6 is (4 x 4 x self.gf_dim*8)**
 e7 = self.g_bn_e7(conv2d(lrelu(e6), self.gf_dim*8, name='g_e7_conv'))
        # e7 is (2 x 2 x self.gf_dim*8)



def conv2d(input_, output_dim, 
           **k_h=5, k_w=5,** d_h=2, d_w=2, stddev=0.02,
           name="conv2d"):

**Comment by yenchenlin** [comment]
TensorFlow 0.11 will fix.

**Comment by powder21** [comment]
It can be solved by changing 
`self.real_data = tf.placeholder(tf.float32,
                                        [self.batch_size, self.image_size, self.image_size,
                                         self.input_c_dim + self.output_c_dim],
                                        name='real_A_and_B_images')`
to :
`self.real_data = tf.placeholder(tf.float32,
                                        [None, None, None,
                                         self.input_c_dim + self.output_c_dim],
                                        name='real_A_and_B_images')`

**Comment by powder21** [comment]
It can be solved by changing
`self.real_data = tf.placeholder(tf.float32, [self.batch_size, self.image_size, self.image_size, self.input_c_dim + self.output_c_dim], name='real_A_and_B_images')`
to :
`self.real_data = tf.placeholder(tf.float32, [None, None, None, self.input_c_dim + self.output_c_dim], name='real_A_and_B_images')`

The same as #3392

**Comment by powder21** [comment]
It can be solved by changing
`self.real_data = tf.placeholder(tf.float32, [self.batch_size, self.image_size, self.image_size, self.input_c_dim + self.output_c_dim], name='real_A_and_B_images')`
to :
`self.real_data = tf.placeholder(tf.float32, [None, None, None, self.input_c_dim + self.output_c_dim], name='real_A_and_B_images')`

The same as #3392 [https://github.com/tensorflow/tensorflow/issues/3392](url)
